% Generate samples from Uniform(0,1) distribution.

% Input:
% n: Number of random numbers generated by Unif(0,1) distribution.
% m: Base, that is used in Random Number Generation (RNG).
% a: Multiplier, that is used in RNG.
% x0: Seed of the RNG.
% Output:
% Y: A length-n vector, generated psuedo-random numbers.
function Y = unif_gen(n, m, a, x0)
    Y = [];
    xo = x0;
    for i = 1:n
        xn = mod(a * xo, m);
        Y = [Y, xn];
        xo = xn;
    end
    Y = Y ./ m;
end
